#!/usr/bin/env python3

import subprocess
from collections import defaultdict

def tree():
    return defaultdict(tree)


def scan(range):
    output = subprocess.check_output(['git', 'diff-tree', '-r', range]).decode('utf-8')
    root = tree()

    for line in output.split('\n'):
        if len(line) == 0:
            break

        details, path = line.split('\t')
        details = details.split(' ')

        mode = details[1]
        sha = details[3]

        ctx = root
        *path, name = path.split('/')
        for part in path:
            ctx = ctx[part]

        ctx[name] = (mode, sha)

    return root

if __name__ == '__main__':
    import pprint
    import sys

    pprint.pprint(scan(sys.argv[1]))
